# Generated by Django 4.2.10 on 2024-03-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_article_image_url_topic_description_topic_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_enrolled', 'Not Enrolled'), ('enrolled', 'Enrolled'), ('completed', 'Completed')], max_length=20)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.user')),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
