# Generated by Django 4.2.10 on 2024-03-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_usertopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopic',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.user')),
            ],
        ),
    ]
