# Generated by Django 4.2.10 on 2024-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_usertopic_status_userchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertopic',
            name='status',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AddConstraint(
            model_name='userchoice',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question'),
        ),
    ]
